[package]
name = "strelka-editor"
version = "0.1.0"
authors = ["khmhmm <khmhmm@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
